name: Deploy docs

on:
  schedule:
    - cron: "0 0 1 1 *"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Prepare Node environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"

      - name: Install NPM packages
        run: npm install

      - name: Build website
        run: bash scripts/build_docusaurus.sh

      - name: Deploy on gh-pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Build for cloudflare-pages
        run: |
          sed -i 's|^const site_url\s*=.*|const site_url="https://pranab.pages.dev";|I' docusaurus.config.js
          bash scripts/build_docusaurus.sh

      - name: Deploy on cloudflare
        if: ${{ github.event_name != 'schedule' }}
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          personal_token: ${{ secrets.CLOUDFLARE_DEPLOY_KEY }}
          publish_dir: build
          external_repository: ${{ github.repository_owner }}/${{ secrets.CLOUDFLARE_REPO_NAME }}
          publish_branch: cf-pages
          destination_dir: ${{ github.event.repository.name }}
          enable_jekyll: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
